name: KONG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  test_api_key: ${{ secrets.KONG_SERVER_SDK_KEY }}
  test_client_key: ${{ secrets. KONG_CLIENT_SDK_KEY }}
  repo_pat: ${{ secrets.KONG_FINE_GRAINED_REPO_PAT }}

jobs:
  KONG:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Get KONG
        run: git clone https://oauth2:${{ secrets.KONG_FINE_GRAINED_REPO_PAT }}@github.com/statsig-io/kong.git .

      - name: Install Deps
        run: npm install

      - name: Setup Go SDK
        run: npm run kong -- setup go -v

      - name: Build Bridge
        run: npm run kong -- build go -v

      - name: Run Tests
        run: npm run kong -- test go -v -r
