name: tests

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0,15 * * *'

jobs:
  jest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: go test statsig_test.go
        env:
          test_api_key: ${{ secrets.SDK_CONSISTENCY_TEST_COMPANY_API_KEY }}
      - run: go test */**.go